controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# index:
#  path: /
#  controller: App\Controller\ProyectoController::index

# cero:
#  path: /cero
#  controller: App\Controller\DefaultController::index

# uno:
#  path: /uno
#  controller: App\Controller\DefaultController::index1

# dos:
#  path: /dos
#  controller: App\Controller\DefaultController::index2

